# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: GPL-3.0-or-later

### CHANGES TO CONFIG.TUTORIAL.YAML ###
retrieve_databundle: # required to be "false" for nice CI test output
  show_progress: false

countries:
- NG

run:
  name: NG
  shared_cutouts: true # set to true to share the default cutout(s) across runs

scenario:
  clusters: [5]

enable:
  retrieve_databundle: false
